name: Deploy Recife Labs - Est치tico 游

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do C칩digo
        uses: actions/checkout@v4

      - name: Deploy via Rsync para a VM Azure
        uses: Burnett01/rsync-deployments@7.0.0
        with:
          # Sincroniza todo o conte칰do do reposit칩rio para a pasta do Nginx
          # Usamos '.' para indicar que queremos enviar os arquivos da raiz
          switches: -avzr --delete
          path: .
          remote_path: /var/www/recifelabs_html/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Exclu칤mos a pasta .git e o pr칩prio workflow do deploy na VM
          args: --exclude=.git* --exclude=.github*